// filepath: d:\React-learn\clone-kid\app\layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/Componets/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Kiddyy-Star",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="https://images.unsplash.com/photo-1662100030158-b8c0900c7c83?w=600&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8aG91c2UlMjBwaW5rJTIwYW5pbWF0ZWR8ZW58MHx8MHx8fDA%3D" type="image/png" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}